# Generated by Django 2.2.4 on 2020-05-26 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_contests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContestsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fb_feed_id', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_feed_id', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.TextField(blank=True, null=True)),
                ('fb_image', models.ImageField(blank=True, null=True, upload_to=user_contests.models.fb_pic_path)),
                ('content', models.TextField(blank=True, null=True)),
                ('fb_likes_count', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_likes_count', models.CharField(blank=True, max_length=150, null=True)),
                ('comments_count', models.CharField(blank=True, max_length=150, null=True)),
                ('provider', models.IntegerField(choices=[(1, 'fb'), (2, 'twitter')])),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
