version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "VierApp-App"
        LoadBalancerInfo:
          ContainerName: "VierApp"
          ContainerPort: 8000
