FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
COPY . .
#RUN pip install -r requirements/celery.txt
ENV CELERY_VERSION 4.3.0

RUN pip install celery=="$CELERY_VERSION" 
#RUN apt update
#RUN apt install -y python-pip
CMD ["celery", "worker"]
